---
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  application:
    name: assets-estate
  datasource:
    url: jdbc:sqlite:assets-estate.db
  data:
    jdbc:
      dialect: org.hibernate.community.dialect.SQLiteDialect
  liquibase:
    change-log: classpath:/db.changelog-master.yml
    contexts: "!test"
    enabled: false
  security:
    login-page: /auth
    open-paths: /*.js,/*.css,/webjars/**,/auth/**,/auth
logging:
  level:
    web: debug
    sql: debug

