spring:
  application:
    name: assets-estate
  datasource:
    url: jdbc:sqlite:assets-estate.db
  data:
    jdbc:
      dialect: org.hibernate.community.dialect.SQLiteDialect
  liquibase:
    change-log: classpath:/db.changelog-master.yml
  security:
    private-key: classpath:/private.pem
    public-key: classpath:/public.pem
    login-page: /auth
    open-paths: /*.js,/*.css,/webjars/**,/auth/*,/auth
logging:
  level:
    web: debug
    sql: debug

